# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartnerSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitrequest',
            name='sr_program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PartnerSearch.Programme'),
        ),
    ]
