# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartnerSearch', '0002_auto_20170111_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='sr_program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PartnerSearch.Programme'),
        ),
    ]
