# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartnerSearch', '0003_interest_sr_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitrequest',
            name='pic_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
